on: push
jobs:
  j:
    runs-on: macos-latest
    steps:
      - run: docker run hello-world
      - run: gem install nokogiri
      - run: ruby --version
      - run: brew install docker
      - run: brew install docker-machine
      - run: brew list docker
      - run: brew info docker
      - run: whoami
      - run: docker-machine create --driver virtualbox default
      - run: docker-machine start default
      - run: eval "$(docker-machine env default)"
      - run: docker run hello-world
